name: fhelper
description: A financial helper made with Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  async: ^2.11.0
  dynamic_color: ^1.6.3
  flex_seed_scheme: ^1.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.2
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  lint: ^2.1.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/attributes.json
