name: fhelper
description: A financial helper made with Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  async: ^2.11.0
  dynamic_color: ^1.6.3
  flex_seed_scheme: ^1.2.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.0.14
  shared_preferences: ^2.1.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0
  lint: ^2.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/attributes.json
